### ISSUE TITLE
NodePollerJob fails if NodeHealthCheckJob doesnt do its job properly

### ISSUE THREAD

**Issue by erindru** [openseedbox/openseedbox#4]
If NodeHealthCheckJob marks a node as down, but fails to mark it as up again when it comes back up, the NodePollerJob will skip polling the node forever and no progress will be updated for any of the torrents running on the node.

Suggested fix: Make NodePollerJob make batch asynchronous requests to avoid blocking all the nodes if one is down, thereby allowing the check for n.isReachable() to be removed.

**Comment by xabolcs** [comment]
As the defunct [`CleanupJob` and `HealthCheckJob`](https://github.com/openseedbox/openseedbox/tree/2cd71ffe99a2ce356c542eadd08094aad6088c7e/app/com/openseedbox/jobs) passed away in commit 73cdc45e904cf4dbe8de953c0e4a197fa4c18b36 this issue is not applicable anymore.

**Comment by xabolcs** [comment]
`NodePollerJob` won't die if one node is down! :+1:
