### ISSUE TITLE
Compile Binaries for ARM

### ISSUE THREAD

**Issue by SanPilot** [openseedbox/openseedbox#40]
I would like to run OpenseedBox on my Raspberry Pi 3, as I'm sure many others will too; however the binaries do not run on ARM chips. If possible, can the binaries be compiled for ARM so that it can be run on devices such as the Raspberry Pi?

**Comment by erindru** [comment]
Openseedbox is a Java app, so it should be compatible with ARM processors. It looks like Transmission can run on ARM processors too. Play! framework 1 is Java / Python, both of which work on ARM.

As the distribution mechanism for Openseedbox is Docker, feel free to contribute an ARM-compatible Dockerfile (you can look at the current one for a basis)

**Comment by SanPilot** [comment]
I'll see what I can do, but honestly don't have any expertise in Docker.

**Comment by erindru** [comment]
You dont strictly need Docker to run it on ARM, however Docker makes it much easier to get a working environment. How are you running it now?

**Comment by SanPilot** [comment]
I tried running it as Docker container, but got an ExecError

**Comment by gregorkistler** [comment]
@xabolcs guess you could close this one here as the `ExecError` is not an issue with Openseedbox. As long as the Docker image uses an architecture which equals the host it will work.

Running natively also shouldn´t be an issue at all. I don´t have a RPi myself but an Overdrive 1000 which is also aarch64 based and it runs as expected.

**Comment by xabolcs** [comment]
@gregorkistler would you mind to provide a mini how-to about this?
I'm about to including it to `Readme`.

**Comment by gregorkistler** [comment]
@xabolcs yes would be possible, just not within the next days. 

I´m awaiting feedback from the vendor of my Overdrive first as it bricked some weeks ago :(
As soon as I have a running machine again I will be able to do it.

**Comment by xabolcs** [comment]
That would be great! Do not hurry! :+1:

**Comment by gregorkistler** [comment]
Got a new Raspberry Pi 3 Model B on Saturday and could do some tests within the past two days.

Assuming you have `sudo` privileges and `git` installed and you use `/data/openseedbox-data` as the download directory you could use those three liners for either armhf based OS (e.g. Raspbian or HypriotOS) or aarch64 (e.g. openSUSE):

armhf
```
git clone https://github.com/openseedbox/openseedbox.git;cd openseedbox;git filter-branch --prune-empty --subdirectory-filter docker HEAD;sed -i 's,java:6-jre,armhf/openjdk:openjdk-6-jre,g' Dockerfile;sudo docker build -t openseedbox/client .;cd $OLDPWD;sudo mkdir -p /data/openseedbox-data
git clone https://github.com/openseedbox/openseedbox-server.git;cd openseedbox-server;git filter-branch --prune-empty --subdirectory-filter docker HEAD;sudo docker build -t openseedbox/server .;cd $OLDPWD
sudo docker run --name openseedbox-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=openseedbox -e MYSQL_PASSWORD=openseedbox -e MYSQL_DATABASE=openseedbox -d gregork/armhf-mysql:5.5;sudo docker run --name openseedbox --link openseedbox-mysql:mysql -p 443:443 -e GOOGLE_CLIENTID=CHANGEME -d openseedbox/client;sudo docker run -v /data/openseedbox-data:/media/openseedbox --name openseedbox-node1 -p 444:443 -e OPENSEEDBOX_API_KEY=node1 -d openseedbox/server
```

aarch64
```
git clone https://github.com/openseedbox/openseedbox.git;cd openseedbox;git filter-branch --prune-empty --subdirectory-filter docker HEAD;sed -i 's,java:6-jre,aarch64/openjdk:openjdk-7-jre,g' Dockerfile;sudo docker build -t openseedbox/client .;cd $OLDPWD;sudo mkdir -p /data/openseedbox-data
git clone https://github.com/openseedbox/openseedbox-server.git;cd openseedbox-server;git filter-branch --prune-empty --subdirectory-filter docker HEAD;sudo docker build -t openseedbox/server .;cd $OLDPWD
sudo docker run --name openseedbox-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=openseedbox -e MYSQL_PASSWORD=openseedbox -e MYSQL_DATABASE=openseedbox -d gregork/aarch64-mysql:5.5;sudo docker run --name openseedbox --link openseedbox-mysql:mysql -p 443:443 -e GOOGLE_CLIENTID=CHANGEME -d openseedbox/client;sudo docker run -v /data/openseedbox-data:/media/openseedbox --name openseedbox-node1 -p 444:443 -e OPENSEEDBOX_API_KEY=node1 -d openseedbox/server
```

What does it do?

1.1 download of the openseedbox git repo
1.2 cd into the downloaded repo
1.3 remove of unnecessary files and folders of the repo
1.4 change of the used container image as there is no multi-arch support in Docker images yet
1.5 build of a local Docker image for the openseedbox/client container
1.6 creation of the torrent download directory
1.7 cd to the previous directory

2.1 download of the openseedbox-server git repo
2.2 cd into the downloaded repo
2.3 remove of unnecessary files and folders of the repo
2.4 change of the used container image as there is no multi-arch support in Docker images yet
2.5 build of a local Docker image for the openseedbox/server container
2.6 cd to the previous directory

3.1 pull of a MySQL image and start as a container
3.2 start of the openseedbox/client container with a link to the MySQL container
3.3 start of the openseedbox/server container

Sadly there aren´t any official MySQL Docker images for any of those CPU architectures and most 3rd party of which I´ve tried from Docker Hub were broken because the maintainer didn´t pay attention or at least didn´t test it afterwards.
In the end I´ve created an image myself which is based on well-known [Resin base images](https://docs.resin.io/runtime/resin-base-images/) and a custom Dockerfile, which can be found [here](https://github.com/gregorkistler/armhf-mysql/blob/master/Dockerfile) and [here](https://github.com/gregorkistler/aarch64-mysql/blob/master/Dockerfile).

Aside of the Google Client ID which needs to be replaced it would work out-of-the-box.

**Comment by xabolcs** [comment]
Awesome! :+1: 

I'm thinking about an `openseedbox-docker` repository to include those `Dockerfile`s.

**Comment by gregorkistler** [comment]
Yes would make sense so that we could keep the source code in the current repositories and provide Dockerfiles in a dedicated one.
Also the whole documentation doesn´t need to be in the Readme.md, we could use the wiki pages for it.

**Comment by xabolcs** [comment]
In the mean time, would you mind to give a try to the PostgreSQL [backend](https://hub.docker.com/r/armhf/postgres/) too? 
If it works I would prefer that for Docker installations.

**Comment by xabolcs** [comment]
Hahh, your {{armhf}} {{Dockerfile}} doesn't builds on my {{x86_64}}. :rofl: 
I'm wondering how to build automatically those ARM Docker images. [Here](https://sedden.github.io/blog/2016/04/11/automated-builds-for-arm-docker-containers-on-intel-hosts/) is a blog post about cross compiling but I'm unsure if that helps.

**Comment by xabolcs** [comment]
Looks like I was able to build both `aarch64` and `armv7hf` version on my `x86_64` which enables me to configure automated builds on Docker Hub. :+1:

**Comment by gregorkistler** [comment]
Cool, I also did some tests today with multiarch image building.

As for PostgreSQL: Would work too. Good thing is that there are official builds like you already figured out for both architectures armhf and aarch64. 
Only the Dockerfile and application.conf need to be touched.

**Comment by xabolcs** [comment]
Why does [fail](https://cloud.docker.com/app/openseedbox/repository/registry-1.docker.io/openseedbox/client/builds/b44d5ca4-5137-4563-b12a-239499ef0d50) Docker Cloud?

**Comment by gregorkistler** [comment]
Automated builds in Docker Cloud seem still not be possible for anything else than x86_64. Found a six months old [thread](https://forums.docker.com/t/automated-build-raspberry-pi-based-image-on-docker-hub/4155/7) in the Docker Community Forums.

So you would need to build it locally or hosted and just push the image to Docker Hub.

**Comment by xabolcs** [comment]
Thank you very much for the reference!

**Comment by xabolcs** [comment]
@gregorkistler , @SanPilot I just pushed some interesting tags to [Docker](https://hub.docker.com/r/openseedbox/client/tags/) [Hub](https://hub.docker.com/r/openseedbox/server/tags/)!

**Comment by gregorkistler** [comment]
LGTM 👍 
Successfully tested all three image tags - client as well as server.

**Comment by xabolcs** [comment]
Great!

Will add some lines to `README.md` and merge the branch!

**Comment by xabolcs** [comment]
[`README.md`](https://github.com/openseedbox/openseedbox/blob/02e335f698158de4999bcf98ca11b1bd37f45e5b/README.md) is up, closing.

**Comment by xabolcs** [comment]
_Offtopic_

gregorkistler commented:
> LGTM :+1:
> Successfully tested all three image tags - client as well as server.

Could you provide me startup times on ARM devices? From `docker start --interactive openseedbox` to `INFO  ~ Listening for HTTP on port 9000 ...`. Thanks!

**Comment by gregorkistler** [comment]
Yes, sure. Just forgot to mention it earlier as I also wondered about it.

aarch64 took 3 minutes and 2 seconds
armhf took 18 minutes and 44 seconds

Both between start of the client docker container until the last mentioned log entry.
Backend container I haven´t checked but it doesn´t take that long.

armhf loses most of the time while precompiling:
```
14:51:48,056 DEBUG ~ Play-Siena: enhancing EnhancedModel com.openseedbox.models.TorrentEvent
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/src/openseedbox-common/lib/ttorrent-1.1.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/play/framework/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
15:06:48,713 INFO  ~ Connected to jdbc:postgresql://openseedboxdb/openseedbox
```

**Comment by xabolcs** [comment]
Uhh, `armhf` is so slow on real hardware too?!

Thanks!

**Comment by gregorkistler** [comment]
Just in case it´s something with the OS itself (I usually use HypriotOS as it works with both architectures) I did the same again on the official Raspbian OS (only armhf available):

Backend container is up and running in 3 minutes and 30 seconds
Frontend container took 10 minutes and 43 seconds

Containers where started at the same time.

Only starting the frontend container (while the database is already running) took 9 minutes and 58 seconds.

**Comment by xabolcs** [comment]
Thanks for the details!

Commit https://github.com/openseedbox/openseedbox/commit/e2a0b751d11195e86bc334a640f130e802495ac6 has set `30min` at startup limit: if OpenSeedbox dies within that time limit, the startup will considered as FAILED, and Superviser will retry.

This should help catching bugs (like the most recent `JPAPlugin`, or earlier the `commons-codec` dependency bug) and avoiding infinite startup loop;
