### ISSUE TITLE
User logoff after successful file download

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#42]
Aside of https://github.com/erindru/openseedbox/issues/41 there is also an annoying bug which I came across.

As soon as you´ve downloaded one file using the web GUI the user session seems to get terminated and you have to log in again.
Attached you will find two screenshots. First one is the file I want to download. After I did it and click on the download link again the login button shows up at the very end.
If you don´t click the download button but let´s say another category after you´ve downloaded a file you simply get redirected directly to the login page.

![screen shot 2016-10-03 at 11 41 41](https://cloud.githubusercontent.com/assets/12155030/19033501/00febb06-895f-11e6-8d38-3b8742851cec.png)
![screen shot 2016-10-03 at 11 42 27](https://cloud.githubusercontent.com/assets/12155030/19033503/011bc19c-895f-11e6-92d5-b596b0031b6c.png)

I´ve tried different users, Google client IDs, container hosts and so on. It´s always the same behaviour.

Would be nice to get this fixed.

**Comment by gregorkistler** [comment]
The only messages I see so far regarding this issue can be found in the browser console - nothing in the application logs itself.

![screen shot 2017-04-30 at 14 21 38](https://cloud.githubusercontent.com/assets/12155030/25564297/7b31b9f0-2db0-11e7-9f13-b4e688df005e.png)
![screen shot 2017-04-30 at 14 21 54](https://cloud.githubusercontent.com/assets/12155030/25564299/7b536686-2db0-11e7-88f4-151a94bd754a.png)
![screen shot 2017-04-30 at 14 25 03](https://cloud.githubusercontent.com/assets/12155030/25564318/e604f4e0-2db0-11e7-8840-784e5f023087.png)

**Comment by xabolcs** [comment]
`signinClicked` error should go away with commit 42e9d0b430350789c5a675df9971c6b89ec44fc7.
But I still have no clues what happening here.

**Comment by gregorkistler** [comment]
Yes, the error message is gone but the behaviour stays the same.

Just out of curiosity, does this happen on your side too?

**Comment by xabolcs** [comment]
Sure, it happens.

**Comment by xabolcs** [comment]
The new Google login (commit 52b30c9fc29ce59aec09d7e965551344582045b9) doesn't help. :cry:

**Comment by gregorkistler** [comment]
At least we have a new shiny login button 😆

**Comment by xabolcs** [comment]
Hmmm, now I can't reproduce with the next environment:
* frontend started from git working tree at `master`, with `play run`
* backend started with `docker run -ti --rm -e OPENSEEDBOX_API_KEY=node1 openseedbox/server`

Downloading doesn't logs me out, but the Info button / Download link only works at third click. The first two click just calls `update`.

Still no have any clues about what happening here.

**Comment by xabolcs** [comment]
Still unable to reproduce, even with the updated [`docker-compose.yml`](https://github.com/openseedbox/openseedbox/commit/2840ea2bef35e2fc217edec4751bc778a7320175):
* `export GOOGLE_CLIENTID=xxxxxxxxxxxxxx`
* `export OPENSEEDBOX_API_KEY=xxxxxxxxxxxxxxxxxxxx`
* `docker-compose -p openseedboxstack -f docker/docker-compose.yml up` from the git working tree
  *  connect `node1` through `http` or `https`
  * configure download path

**Comment by gregorkistler** [comment]
Interesting ... as I still have the same issue as before.

Doesn´t matter if I use a container or start it natively. Used both approaches you´ve described in your last two comments and I still get logged out after the first download.

Cleared all existing docker images and pulled the latest available ones.
Cleared the browser cache of Safari and Chrome.

No dice...

**Comment by xabolcs** [comment]
I was able to reproduce again! :+1: :trollface: 
Just started both backend and frontend from IDE.

**Comment by xabolcs** [comment]
Found other steps to reproduce :joy: 
1. login to client e.g. `http://localhost:9000`
1. get server status url, e.g. `http://localhost:9001/status?ext=xml&api_key=vm1`
1. call it
1. check the client

**OK, I got it! :sunglasses:** 
The root cause is that the client and the server are on the same domain, only the port differs!
### Therefore the cookies sent by the two different Play! framework clashes! :collision:

See StackOverflow question _[Are HTTP cookies port specific?](https://stackoverflow.com/questions/1612177/are-http-cookies-port-specific)_!

>     1. Introduction
> ...
>
> For historical reasons, cookies contain a number of security and privacy infelicities. For example, a server can indicate that a given cookie is intended for "secure" connections, but the Secure attribute does not provide integrity in the presence of an active network attacker. **Similarly, cookies for a given host are shared across all the ports on that host, even though the usual "same-origin policy" used by web browsers isolates content retrieved via different ports.**

>     8.5. Weak Confidentiality
>
> **Cookies do not provide isolation by port.** If a cookie is readable by a service running on one port, the cookie is also readable by a service running on another port of the same server. If a cookie is writable by a service on one port, the cookie is also writable by a service running on another port of the same server. For this reason, servers SHOULD NOT both run mutually distrusting services on different ports of the same host and use cookies to store security sensitive information.

**Comment by gregorkistler** [comment]
Nice catch! 
Thanks to these details I´ve fixed it already on my end 😄 
I simply set an unique cookies via each application.conf, e.g.:

`application.session.cookie=PLAYFRONTEND`
`application.session.cookie=PLAYBACKEND`

if there would be more than just one backend then each backends get a different one
`application.session.cookie=PLAYBACKEND1`
`application.session.cookie=PLAYBACKEND2`
`application.session.cookie=PLAYBACKENDn`

**Comment by xabolcs** [comment]
:+1: 

Yes, that's the correct resolution of this problem!

**Comment by xabolcs** [comment]
PR (containing `conf/application.conf.default`, `docker/application.conf` and `run.sh` changes) is coming soon.

**Comment by gregorkistler** [comment]
LGTM 👍 

Will close the issue as it´s finally fixed.
