### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#44]
Ever tried to run the frontend against anything else than MySQL/MariaDB?
Since PostgreSQL doesn´t allow tables called 'user' I had to change the table name in the Users.java file to 'users'. 
At the first start all tables and columns were created. During the login the new 'users' table got filled the same way than in MySQL but the login doesn´t work.
I end up again at the login button but there isn´t any error message at all.

**Comment by gregorkistler** [comment]
Looks like two inserts ignore the PostgreSQL sequence and don´t use starting values for the primary key and start with a 0 instead of a 1 which causes the login issue.
Once I´ve changed the PK to 1 for the first user account I can log in as expected. If I use another account to log in it will run into the same issue.
If I wouldn´t change the PK and try to log in both accounts will overwrite their attributes at each login try.

The second table where the same happens is the torrent table.
Every torrent you add will overwrite the last one added because the PK will always be 0 which causes an error regarding the torrent hash.

**Comment by xabolcs** [comment]
The users/login bug was an easy one.
The torrent bug seems like harder. Continue digging ...

**Comment by xabolcs** [comment]
This wasn't true. They are the same.

**Comment by gregorkistler** [comment]
Sweet! Thank you.
Mind if you share the necessary changes?

**Comment by xabolcs** [comment]
The changes are done, but not yet committed, will put it on a branch and open a PR here later today.

**Comment by gregorkistler** [comment]
Cool. The project seems to be dead since months but at least I can check the PR.

**Comment by xabolcs** [comment]
PR #45 with Postgres compatibility fixes has merged. May I close this issue, @gregorkistler?

**Comment by gregorkistler** [comment]
Still had some issues during the login like the following:

> Apr 19 11:09:39 172.18.0.1 ui[2319]: 09:09:39,424 ERROR ~ 
> Apr 19 11:09:39 172.18.0.1 ui[2319]: 
> Apr 19 11:09:39 172.18.0.1 ui[2319]: @73lif87lf
> Apr 19 11:09:39 172.18.0.1 ui[2319]: Internal Server Error (500) for request GET /auth/authenticate?id_token=<SOME_TOKEN>
> Apr 19 11:09:39 172.18.0.1 ui[2319]: 
> Apr 19 11:09:39 172.18.0.1 ui[2319]: Execution exception (In /app/controllers/Auth.java around line 57)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: NullPointerException occured : null
> Apr 19 11:09:39 172.18.0.1 ui[2319]: 
> Apr 19 11:09:39 172.18.0.1 ui[2319]: play.exceptions.JavaExecutionException
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at Invocation.HTTP Request(Play!)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: Caused by: java.lang.NullPointerException
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at controllers.Auth.authenticate(Auth.java:57)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
> Apr 19 11:09:39 172.18.0.1 ui[2319]: #011... 1 more

but likely that I mixed up some code from my own repo. Will fetch the latest changes. If necessary I will reopen or create a new issue.
Thanks so far.

**Comment by gregorkistler** [comment]
Okay got it. The issue was fixed a couple of days ago after the PR with 02a23b97bc6d239e5c2691897d892a2f1e26a507 👍

**Comment by xabolcs** [comment]
Yeah, my bad! Sorry for that! :blush:
