### ISSUE TITLE
Group related glitch in the UI while using Memcached

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#48]
Memcached usually isn´t enabled by default. If you enable it you will notice, that in case you add OR remove a group it will have an effect only after you´ve logged out and logged in again.
Otherwise the new group won´t show up or the other why around it will still show up even if it was already removed.

Doesn´t happen while Memcached is disabled.

**Comment by xabolcs** [comment]
Interesting.
Please provide Play version and STR!
Thanks!

**Comment by gregorkistler** [comment]
I had this already one or two years ago, just forgot to create an issue.

Happens with Play! version 1.2.5 up to 1.2.7.2
Containerized or natively running has the same effect.

Mind if I ask what a STR is in this regard?

**Comment by xabolcs** [comment]
**S**teps **T**o **R**eproduce. :)

Simply enabling [memcached](https://www.playframework.com/documentation/1.2.x/configuration#memcachedconfig) through `memcached=enabled` without any other configuration triggers the bug?

**Comment by gregorkistler** [comment]
Ahh okay :)
Exactly like described there.

1. install memcached
2. edit applications.conf and add:
memcached=enabled
memcached.host=127.0.0.1:11211
3. restart play application
4. add a new group in the UI 

Expected result:
Newly added group is visible immediately - or at least after a refresh of the page

**Comment by xabolcs** [comment]
@gregorkistler please take a look at my [branch-issue-48-memcached-torrentgroups](https://github.com/xabolcs/openseedbox/tree/branch-issue-48-memcached-torrentgroups) branch for proposed fix!

**Comment by gregorkistler** [comment]
LGTM

The only time where it still happens is in the following scenario:

1. Add a torrent to any of your existing groups
2. Select the torrent or use the select all checkbox
3. Click at 'With Selected' dropdown
4. Enter any group name into the 'New Group' field and click 'Add to Group'

Expected result:
Torrent will be moved into the new group and the new group is visible at the left side.

Actual result:
You find yourself in the new group and see the moved torrent but the group is missing at the left side.
Once you click back at any other group you won´t find your torrent anymore unless you logout and login again or you append `?group=<group_name>` to the URL or click the back button of the browser.

**Comment by xabolcs** [comment]
@gregorkistler next round! Thanks for catching!

**Comment by gregorkistler** [comment]
I´ve checked out your last commit and it looks a little bit different but mostly the same than described in my previous post under 'Actual result'.

If you do the same steps 1 to 4 again you will see the following now:
You find yourself in the new group but the torrent wasn´t moved (that´s the only difference compared to the previous commit) and you still don´t see the newly created group unless you log out and log in again.

**Comment by xabolcs** [comment]
Yeah, typo.
Give it a try, please!

**Comment by gregorkistler** [comment]
Works, thank you.

**Comment by xabolcs** [comment]
:+1:
