### ISSUE TITLE
Newly introduced node properties don´t work as expected

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#49]
Today I´ve pulled the changes made a couple of days ago. I like the idea of having an internal communication between the UI and backend nodes and a public one only for user interaction like download.

After I´ve edited the settings of an existing node and left the value of the field `Host / IP Address : Port For Downloads` empty I couldn´t download anything anymore because my browser pointed to a file location like 

> http://download/821735ee68379684c0aad5c1e30c07677429b928?name=debian-8.7.1-arm64-netinst.iso

The field description seems not quite correct at the moment: 

> optional, leave empty if it's the same

Currently it doesn´t really matter if it´s the same or not. In any case it will lead to an empty value regarding the ip address/hostname/FQDN which of course ends in a download URL which doesn´t exist.

**Comment by xabolcs** [comment]
Oh! :(
Thanks for reporting.

**Comment by xabolcs** [comment]
It works for me. :(
What next?

Could you provide a STR?

**Comment by xabolcs** [comment]
@gregorkistler please check my proposed fix on [branch-issue-49-public-channel-isempty](/xabolcs/openseedbox/tree/branch-issue-49-public-channel-isempty) branch!

**Comment by gregorkistler** [comment]
Yes that solves it, thank you. 
The field description would be still irritating as the field won´t stay empty after you´ve saved the form and edit it again but that´s okay for me.
Functionality matters :)

**Comment by xabolcs** [comment]
Thanks!

Empty field comes with another train! ;)

**Comment by xabolcs** [comment]
Fixed by commit ac26959fed542048feb968e141f5290be890f8d8.
