### ISSUE TITLE
Feature request: independent schemes regarding node download and communication

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#50]
Aside of #49 I´ve also had an issue with the scheme setting. Currently you can only define http or https which will be used for both address:port values, the one for communication as well as downloads.

In my setup I actually would like to use http for node communication - no need for https because the docker network takes care of it - and https for downloads.
As I rewrite http to https via proxy for public access it´s not an issue, just wanted to address this as it could be useful for others too.

**Comment by xabolcs** [comment]
Yeah, the model has it already, but forgot to add to view.
My bad. :)

Thanks for reporting!

**Comment by gregorkistler** [comment]
Alright, great :)

**Comment by xabolcs** [comment]
@gregorkistler please check my proposed fix on my [branch-issue-50-edit-download-scheme](/xabolcs/openseedbox/tree/branch-issue-50-edit-download-scheme) branch!

**Comment by gregorkistler** [comment]
Perfect, thank you.

**Comment by xabolcs** [comment]
Fixed by commit 8a68a6c4ee59578dcac11f8709babf0873e50a7a.
