### ISSUE TITLE
Rebase Docker images to buster or bullseye

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#69]
- already started by #68 
- avoid #66 for now :wink: 
- use Java 8 (but not Play! 1.5, #62)

Refreshing Travis CI integration may be done later.

**Comment by stickz** [comment]
If you go up to Bullseye, it's required to resolve a compatibility issue with transmission-3.0.0 that breaks to tracker stats on the WebUI. Java will throw an IllegalFormatException because it expects a boolean somewhere but receives a number.

**Comment by stickz** [comment]
I wanted to stay on stable Buster with latest version of transmission, so I made a script for openseedbox-server to build it.
```
# Install build tools
RUN apt-get -qq update \
	&& apt-get -qq install -y \
	ca-certificates libcurl4-openssl-dev libssl-dev pkg-config build-essential 
	
# Make & Install Libevent
Run cd /var/tmp \
	&& wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz \
	&& tar xzf libevent-2.1.12-stable.tar.gz \
	&& cd libevent-2.1.12-stable \
	&& CFLAGS="-O2 -march=native" ./configure --prefix=/usr --disable-static && make && make install
	
# Make & Install transmission	
RUN cd /var/tmp \
	&& wget https://github.com/transmission/transmission-releases/raw/master/transmission-3.00.tar.xz \
	&& tar xvf transmission-3.00.tar.xz \
	&& cd transmission-3.00 \
	&& CFLAGS="-O2 -march=native" ./configure --disable-gtk --disable-nls --disable-cli --disable-mac --enable-daemon \
	&& make && make install

# Clean up after making is done
RUN apt-get -qq purge -y \
	libcurl4-openssl-dev libssl-dev pkg-config build-essential \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by xabolcs** [comment]
@stickz , do you need specifically Debian or may I use Alpine or even Distroless Images?

**Comment by stickz** [comment]
I just need the latest version of transmission. It doesn't really matter how it's delivered, as long everything is stable.

**Comment by xabolcs** [comment]
I hoped so! Thanks! :+1:

**Comment by gregorkistler** [comment]
An image size comparison would be great ;)

**Comment by xabolcs** [comment]
Sure! Thanks for joining the talk!

**Comment by xabolcs** [comment]
@gregorkistler 

Debian Buster:
```
$ docker images openseedbox-*
REPOSITORY            TAG       IMAGE ID       CREATED          SIZE
openseedbox-aarch64   latest    2c7ee0622139   26 seconds ago   468MB
openseedbox-armhf     latest    d9a75845c552   4 minutes ago    409MB
openseedbox-amd64     latest    e214ced1a75a   18 minutes ago   462MB
```

Alpine Linux 3.11:
```
$ docker images openseedbox-amd64
REPOSITORY          TAG       IMAGE ID       CREATED         SIZE
openseedbox-amd64   latest    887e7eadc02d   6 seconds ago   352MB
```

Converting `apt-get install` to `apk add` was an average work:
```
$ git diff --stat 
 docker/amd64.Dockerfile | 34 ++++++++++------------------------
 1 file changed, 10 insertions(+), 24 deletions(-)
```

I tested Alpine 3.11 because of Transmission < 3.00.

---

Once they drop OpenJDK 8, then the manual install wouldn't worth the work:
```
$ docker images openseedbox-amd64
REPOSITORY          TAG       IMAGE ID       CREATED          SIZE
openseedbox-amd64   latest    36761398e834   16 seconds ago   495MB
```
```
$ git diff --stat 
 docker/amd64.Dockerfile | 77 +++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------
 1 file changed, 53 insertions(+), 24 deletions(-)
```

**Comment by gregorkistler** [comment]
Thanks @xabolcs. Looks promising. ~110 MB (amd64 and aarch64) in size between Alpine and Debian.
Any reason why you use 3.11 and not 3.12/latest?

**Comment by xabolcs** [comment]
Read earlier comments for reasoning! :wink:

**Comment by gregorkistler** [comment]
Okay, got it: `<` != `>` :) 
Just thought @stickz wanted to go on with Transmission 3.00?

**Comment by stickz** [comment]
I'm going to see if I can debug the issue with GSON preventing tracker statistics from working on Transmission 3.00, when I get some spare time. One of the datatypes on the JSON response from the transmission web service most likely changed in this release. A value somewhere is trying to be de-serialized as an Integer, when it should in-fact be de-serialized as a Boolean.

**Comment by gregorkistler** [comment]
@stickz I've created a separate issue regarding Transmission 3.0.0 support.

**Comment by xabolcs** [comment]
Btw commit ff77348a2adaf1eea63bccb292240592ce49e8ea has green lights from CI.
Moving to OpenSeedbox Server.

I will finish the Alpine experiment after that.

**Comment by xabolcs** [comment]
`openseedbox/client` updated :tada: 

![Screenshot_2021-01-02 openseedbox client Tags - Docker Hub](https://user-images.githubusercontent.com/568751/103458147-a1396300-4d05-11eb-90d8-12c6b0959703.png)

**Comment by gregorkistler** [comment]
Sweet! Thank you :)

**Comment by xabolcs** [comment]
Fix for `openseedbox-server` pushed to my fork, CI is testing: https://travis-ci.org/github/xabolcs/openseedbox-server/builds/752524823

Locally built Docker images looks good.
```
$ docker images openseedbox-server-*
REPOSITORY                   TAG       IMAGE ID       CREATED              SIZE
openseedbox-server-amd64     latest    fe0297bee250   16 seconds ago       468MB
openseedbox-server-armv7hf   latest    ece5ff4f3bb3   About a minute ago   427MB
```

**Comment by xabolcs** [comment]
Pushed, `openseedbox-server` CI: https://travis-ci.org/github/openseedbox/openseedbox-server/builds/752536343

**Comment by xabolcs** [comment]
@stickz , @gregorkistler Docker images for `openseedbox-server` are out!
Please test!

![Screenshot_2021-01-02 openseedbox server Tags - Docker Hub](https://user-images.githubusercontent.com/568751/103461355-144ed380-4d1e-11eb-9f28-1b601ab12afc.png)

**Comment by gregorkistler** [comment]
LGTM

Tested both Arm architectures on a Raspberry Pi 3b+ with current Raspberry Pi OS images as well as the aarch64 containers on a Nvidia Xavier NX.

**Comment by xabolcs** [comment]
> LGTM

Thanks, closing!
