### ISSUE TITLE
Update distribution: Java 11,  Play 1.4.6, nginx 1.20.2, ...

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#77]
@gregorkistler wrote in #62:

> Fun fact:
> I'm running the frontend and backend with the latest Java 11 version via Play! 1.4.6 without any issues :sweat_smile: No single code change was necessary so far :partying_face: This also reduces the image size compared to Java 8 by up to 65 MB depending on the architecture.

And then:
> My first few tries also ended up in blown up images :sweat_smile: Then I remembered they introduced [jlink](https://docs.oracle.com/javase/9/tools/jlink.htm) with Java 9 where you can have a smaller footprint by removing unnecessary modules, headers, man pages and also compress modules.
> 
> Currently I'm using something like: `jlink --add-modules ALL-MODULE-PATH --output /usr/lib/jvm/<CUSTOM_JDK_DIR> --strip-debug --no-man-pages --compress=2;` I'm simply using all modules as I didn't want to do trial & error to figure out which modules the project really relies on and which not. I also didn't strip headers as I need it to compile Tomcat so I could still optimise it a little bit further.
> 
> `armhf:`
> 
> ```
> REPOSITORY             TAG              IMAGE ID       CREATED        SIZE
> openseedbox-backend    1.10.28-debian   d1bae87541c2   13 days ago    185MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-frontend   1.10.28-debian   5aab7d49a843   13 days ago    194MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-backend    1.10.27-debian   c089ffc6ec10   13 days ago    338MB   <-- Java 11.0.14.1
> openseedbox-frontend   1.10.27-debian   6b398dee4afe   13 days ago    348MB   <-- Java 11.0.14.1
> openseedbox-backend    1.10.26-debian   2be0008eb39a   4 weeks ago    199MB   <-- Java 8u332
> openseedbox-frontend   1.10.26-debian   88b1da4249b0   4 weeks ago    209MB   <-- Java 8u332
> ```
> 
> `arm64:`
> 
> ```
> REPOSITORY             TAG              IMAGE ID       CREATED        SIZE
> openseedbox-backend    1.10.28-debian   5097ae22d062   13 days ago    219MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-frontend   1.10.28-debian   0335cf50c704   13 days ago    229MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-backend    1.10.27-debian   add0aae0bd31   13 days ago    392MB   <-- Java 11.0.14.1
> openseedbox-frontend   1.10.27-debian   2270c1f35626   13 days ago    401MB   <-- Java 11.0.14.1
> openseedbox-backend    1.10.26-debian   9e743fc57dda   4 weeks ago    228MB   <-- Java 8u332
> openseedbox-frontend   1.10.26-debian   bbad678e676d   4 weeks ago    237MB   <-- Java 8u332
> ```
> 
> `amd64:`
> 
> ```
> REPOSITORY             TAG              IMAGE ID       CREATED        SIZE
> openseedbox-backend    1.10.28-debian   fd76e8cf1123   13 days ago    231MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-frontend   1.10.28-debian   7f5b49ef6a5c   13 days ago    240MB   <-- Java 11.0.14.1 jlink customized JDK
> openseedbox-backend    1.10.27-debian   b2d85754a53f   13 days ago    405MB   <-- Java 11.0.14.1
> openseedbox-frontend   1.10.27-debian   c1545f535e05   13 days ago    415MB   <-- Java 11.0.14.1
> openseedbox-backend    1.10.26-debian   9a58cfc6ee04   4 weeks ago    295MB   <-- Java 8u332
> openseedbox-frontend   1.10.26-debian   54f7b9af1baa   4 weeks ago    305MB   <-- Java 8u332
> ```

**Comment by xabolcs** [comment]
Continuing from #62 .... I'm still unlucky:
```
openseedboxclient   buster-java11-play146   a89586261044   7 seconds ago   879MB
```

From:
```Dockerfile
RUN apt-get -qq update && apt-get -qq install -y \
		openjdk-11-jdk-headless ca-certificates-java \
	&& jlink --add-modules ALL-MODULE-PATH --output /java/ --strip-debug --no-man-pages --compress=2 \
	&& apt-get purge -y openjdk-11-jdk-headless openjdk-11-jre-headless \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by gregorkistler** [comment]
Yep, there is something completely wrong 🙈: https://github.com/docker-library/openjdk/issues/217

After creating a custom JDK (amd64):

```
root@56432cc67c62:/java/lib/server# ls -alh
total 408M
drwxr-xr-x 2 root root 4.0K May  1 09:20 .
drwxr-xr-x 6 root root 4.0K May  1 09:20 ..
-rw-r--r-- 1 root root 1.3K May  1 09:20 Xusage.txt
-rw-r--r-- 1 root root  31K May  1 09:20 libjsig.so
-rw-r--r-- 1 root root 408M May  1 09:20 libjvm.so                   <-- errrrrr, what?!
root@56432cc67c62:/java/lib/server# strip -p --strip-unneeded libjvm.so 
root@56432cc67c62:/java/lib/server# ls -alh
total 19M
drwxr-xr-x 2 root root 4.0K May  1 09:29 .
drwxr-xr-x 6 root root 4.0K May  1 09:20 ..
-rw-r--r-- 1 root root 1.3K May  1 09:20 Xusage.txt
-rw-r--r-- 1 root root  31K May  1 09:20 libjsig.so
-rw-r--r-- 1 root root  19M May  1 09:20 libjvm.so                   <-- 👍
```

I personally didn't encounter this as I'm using Azul Zulu or Amazon Corretto OpenJDK since a couple of years now.

But even after fixing it I'm still ending up with a slightly bigger image size than with Java 8:
```
REPOSITORY          TAG             IMAGE ID       CREATED          SIZE
openseedboxclient   buster-java11   d03f874f1b35   2 minutes ago    481MB
openseedboxclient   buster-java8    d84a00b35fb4   2 hours ago      475MB
```

```diff
--- amd64.Dockerfile	2022-05-01 09:47:57.675550484 +0000
+++ Dockerfile.buster_play-1.3.4_java-11	2022-05-01 09:48:58.356387853 +0000
@@ -1,5 +1,7 @@
 FROM balenalib/amd64-debian:buster
 
+ENV JAVA_HOME /java
+
 ENTRYPOINT /usr/bin/supervisord
 
 # Default values for config environment variables
@@ -16,7 +18,7 @@
 
 # Install runtime packages
 RUN apt-get -qq update \
-	&& apt-get -qq install -y \
+	&& apt-get -qq install --no-install-recommends -y \
 		curl wget unzip git \
 		python supervisor \
 		zlibc zlib1g \
@@ -24,12 +26,11 @@
 	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 # Install openjdk from AdoptOpenJDK
-RUN apt-get -qq update && apt-get -qq install -y gnupg \
-	&& wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - \
-	&& echo deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb $(. /etc/os-release && echo $VERSION_CODENAME) main > /etc/apt/sources.list.d/adoptopenjdk.list \
-	&& apt-get -qq update \
-	&& apt-get -qq install -y adoptopenjdk-8-hotspot-jre libatomic1 \
-	&& apt-get -qq purge -y gnupg \
+RUN apt-get -qq update && apt-get -qq install --no-install-recommends -y \
+		openjdk-11-jdk-headless ca-certificates-java binutils \
+	&& jlink --add-modules ALL-MODULE-PATH --output /java/ --strip-debug --no-man-pages --compress=2 \
+	&& strip -p --strip-unneeded $JAVA_HOME/lib/server/libjvm.so \
+	&& apt-get purge -y openjdk-11-jdk-headless openjdk-11-jre-headless binutils \
 	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 # Install play
@@ -53,7 +54,7 @@
 
 # Download and compile nginx
 RUN apt-get -qq update \
-	&& apt-get -qq install -y \
+	&& apt-get -qq install --no-install-recommends -y \
 		build-essential libpcre3-dev libssl-dev zlib1g-dev \
 	&& apt-get -y clean \
 	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
```

We could also get rid of a couple of Play! files and folders:
`&& unzip -q play.zip -x play-1.3.4/documentation/* play-1.3.4/samples-and-tests/* \`
which saves another 26M 🥳

```
REPOSITORY          TAG             IMAGE ID       CREATED          SIZE
openseedboxclient   buster-java11.  256cee347941   5 seconds ago    455MB
```

**Comment by xabolcs** [comment]
Awesome! Thank you helping out! :tada:

**Comment by xabolcs** [comment]
> I personally didn't encounter this as I'm using Azul Zulu or Amazon Corretto OpenJDK since a couple of years now.

You gave me a hint to use AdoptOpenJDK's successor: Adoptium:

```
$ docker images openseedboxclient:*
REPOSITORY          TAG                                  IMAGE ID       CREATED             SIZE
openseedboxclient   issue-77-temurin11-jlink-play146     96eca8b6e6e4   3 seconds ago       450MB
openseedboxclient   issue-77-temurin11-play146           e71835540e8d   4 minutes ago       678MB
openseedboxclient   issue-77-jre11-play146               be1964467def   45 minutes ago      556MB
openseedboxclient   issue-77-jdk11-jlink-strip-play146   f86996e5fc0d   About an hour ago   482MB
openseedboxclient   buster-java8                         a560827d5f38   21 hours ago        473MB
```

[Adoptium provides Linux (rpm/deb) installers](https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/ "Eclipse Temurin Linux (RPM/DEB) installer packages"): but full JDK only, not a slim JRE.

But JDK could be `jlink`-ed, and voila! :tada:

**Comment by gregorkistler** [comment]
Cool, that looks way more promising 😄

**Comment by xabolcs** [comment]
Wanna test? :wink: 

> [**xabolcs:77-update-distribution-java-play-and-others**](https://github.com/xabolcs/openseedbox/tree/77-update-distribution-java-play-and-others) had recent pushes 1 minute ago

**Comment by gregorkistler** [comment]
Sure thing! 🙂

Created a PR in your repo with some fixes. I'm not quite sure about the remaining JVM options in the run.sh [script](https://github.com/openseedbox/openseedbox/blob/2b9281691e6c3a5e6137122122c35f3db06d41de/docker/run.sh#L45).

https://github.com/openseedbox/openseedbox/blob/2b9281691e6c3a5e6137122122c35f3db06d41de/docker/run.sh#L45

Especially the usage of SerialGC instead of the meanwhile (since Java 9) default G1CC.

**Comment by xabolcs** [comment]
> I'm not quite sure about the remaining JVM options in the run.sh

Yup!
* `-XX:+UnlockExperimentalVMOptions` was for enabling `-XX:+UseCGroupMemoryLimitForHeap`
* `-XX:+UseCGroupMemoryLimitForHeap` was for ["Java SE support for Docker CPU and memory limits"](https://blogs.oracle.com/java/post/java-se-support-for-docker-cpu-and-memory-limits) (see commit 9fdf38ed8db95527eb43c3a31a0684be14472643), superseded now by `UseContainerSupport` which is default enabled.
* `-XshowSettings:vm` is to verify that does the Docker container take into account the cgroup limits.
* `-XX:+UseSerialGC` looks like is also superseded with G1CC

**Comment by gregorkistler** [comment]
> > I'm not quite sure about the remaining JVM options in the run.sh
> 
> Yup!
> 
> * `-XX:+UnlockExperimentalVMOptions` was for enabling `-XX:+UseCGroupMemoryLimitForHeap`
> * `-XX:+UseCGroupMemoryLimitForHeap` was for ["Java SE support for Docker CPU and memory limits"](https://blogs.oracle.com/java/post/java-se-support-for-docker-cpu-and-memory-limits) (see commit [9fdf38e](https://github.com/openseedbox/openseedbox/commit/9fdf38ed8db95527eb43c3a31a0684be14472643)), superseded now by `UseContainerSupport` which is default enabled.
> * `-XshowSettings:vm` is to verify that does the Docker container take into account the cgroup limits.
> * `-XX:+UseSerialGC` looks like is also superseded with G1CC

Perfect, thank you 🙂

**Comment by xabolcs** [comment]
@gregorkistler, pushed all tags for `openseedbox/client`. :ok_hand:

**Comment by gregorkistler** [comment]
Great, thank you. Will have a look at it later today. 🙂

**Comment by gregorkistler** [comment]
Tested all three architectures.
LGTM :)

Suppose we can apply the same changes also to the backend.

**Comment by xabolcs** [comment]
```bash
$ docker images openseedbox/server:*
REPOSITORY           TAG          IMAGE ID       CREATED         SIZE
openseedbox/server   dockerfile   bd272102d3d1   4 minutes ago   435MB
openseedbox/server   latest       8a2c4a8dfe5d   15 months ago   469MB
```

And looks good:
```
2022-05-11 21:46:45,759 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2022-05-11 21:46:45,759 INFO Set uid to user 0 succeeded
2022-05-11 21:46:45,769 INFO RPC interface 'supervisor' initialized
2022-05-11 21:46:45,769 INFO supervisord started with pid 1
2022-05-11 21:46:46,770 INFO spawned: 'supervisord-stopper' with pid 8
2022-05-11 21:46:46,771 INFO spawned: 'nginx' with pid 9
2022-05-11 21:46:46,772 INFO spawned: 'openseedbox' with pid 10
Play secret has not been generated; generating
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.4.6, https://www.playframework.com
~
~ Generating the secret key...
~ Keep the secret : 6OiCz1y0vvUPHuFWT63W0ddlA3MJTFOci8pQYhZ80O99l95c7x7JzWKzKk8YV4op
~
Starting play in /src/openseedbox-server
VM settings:
    Max. Heap Size (Estimated): 7.80G
    Using VM: OpenJDK 64-Bit Server VM

21:46:47,676 INFO  ~ Starting /src/openseedbox-server
:: loading settings :: url = jar:file:/play/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
2022-05-11 21:46:47,810 INFO success: supervisord-stopper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-11 21:46:47,810 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
...
2022-05-11 21:49:39,663 WARN received SIGTERM indicating exit request
2022-05-11 21:49:39,663 INFO waiting for nginx, openseedbox, supervisord-stopper to die
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.4.6, https://www.playframework.com
~
~ Ctrl+C to stop
~ 
~ using java version "11.0.14.1"
2022-05-11 21:49:39,671 INFO stopped: openseedbox (exit status 0)
2022-05-11 21:49:39,672 INFO stopped: nginx (exit status 0)
2022-05-11 21:49:39,673 INFO stopped: supervisord-stopper (terminated by SIGTERM)
```

**Comment by xabolcs** [comment]
@gregorkistler, [backend images](https://hub.docker.com/r/openseedbox/server/tags) are fresh! :+1:

**Comment by gregorkistler** [comment]
Cool, thanks. Will have a look at it tonight :)

I meanwhile figured out which Java modules we really need so we can even further reduce the image size.

```
docker image ls -f reference='openseedbox/client*'
REPOSITORY              TAG       IMAGE ID       CREATED             SIZE
openseedbox/client-v2   latest    f298b4597e09   About an hour ago   401MB
openseedbox/client      latest    c54962f7f90a   8 days ago          432MB
```

So another 31 MB for the client container on amd64 🎉

Mandatory modules according to jdeps:
```
java.base
java.compiler
java.datatransfer
java.desktop
java.instrument
java.logging
java.management
java.management.rmi
java.naming
java.prefs
java.rmi
java.scripting
java.security.jgss
java.security.sasl
java.sql
java.sql.rowset
java.transaction.xa
java.xml
java.xml.crypto
jdk.jdi
jdk.management
jdk.unsupported
```

Once I've built a custom JDK with those modules I was able to compile the app, start the app and log in but the node/backend health check failed - so clearly one or the other module was still missing.
After doing some trial and error I figured out we also need

`jdk.crypto.cryptoki` which didn't show up as a dependancy.

Once added to the module's list the health check worked again.

Docker file changes look like this:

```diff
diff --git a/docker/amd64.Dockerfile b/docker/amd64.Dockerfile
index 4129042..72288db 100644
--- a/docker/amd64.Dockerfile
+++ b/docker/amd64.Dockerfile
@@ -31,7 +31,7 @@ RUN apt-get -qq update && apt-get -qq install -y gnupg \
        && echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list \
        && apt-get -qq update \
        && apt-get -qq install -y temurin-11-jdk \
-       && jlink --add-modules ALL-MODULE-PATH --output /java/ --strip-debug --no-man-pages --compress=2 \
+       && jlink --add-modules java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.jdi,jdk.management,jdk.unsupported,jdk.jartool,jdk.crypto.cryptoki --output /java/ --strip-debug --no-man-pages --compress=2 \
        && apt-get -qq purge -y gnupg temurin-11-jdk \
        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

I will do some more tests within the next couple of days also on the other CPU architectures.

**Comment by xabolcs** [comment]
> Once I've built a custom JDK with those modules I was able to compile the app, start the app and log in but the node/backend health check failed - so clearly one or the other module was still missing. After doing some trial and error I figured out we also need `jdk.crypto.cryptoki` which didn't show up as a dependancy.
> 
> Once added to the module's list the health check worked again.

When you are ready to publish your work, please describe this `jdeps` dependency discovery method in the commit description!
I'm asking this because there will be time when this list got outdated and need to be refreshed.

**Comment by gregorkistler** [comment]
Yes, good point, thanks.

**Comment by gregorkistler** [comment]
> @gregorkistler, [backend images](https://hub.docker.com/r/openseedbox/server/tags) are fresh! 👍

LGTM - haven't seen any issues so far 🥳
