### ISSUE TITLE
Docker: This proxy request is not authorized: 172.20.0.3

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#91]
The war packaged application behind reverse proxy doesn't always work well:

### Message
java.lang.RuntimeException: This proxy request is not authorized: 172.20.0.3
### Exception
```
jakarta.servlet.ServletException: java.lang.RuntimeException: This proxy request is not authorized: 172.20.0.3
	play.server.ServletWrapper.service(ServletWrapper.java:175)
	jakarta.servlet.http.HttpServlet.service(HttpServlet.java:799)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```
### Root Cause
```
java.lang.RuntimeException: This proxy request is not authorized: 172.20.0.3
	play.mvc.Http$Request.parseXForwarded(Http.java:383)
	play.mvc.Http$Request.createRequest(Http.java:368)
	play.server.ServletWrapper.parseRequest(ServletWrapper.java:303)
	play.server.ServletWrapper.service(ServletWrapper.java:147)
	jakarta.servlet.http.HttpServlet.service(HttpServlet.java:799)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
```
### Note
 The full stack trace of the root cause is available in the server logs.

[Because of](/openseedbox/openseedbox/blame/956fb6d2d3a741effafd1511d3a103196a301c9c/docker/application.conf#L23):
```
XForwardedSupport=127.0.0.1
```

**Comment by xabolcs** [comment]
Hausaufage for the reader to generate IP addesses from a range.

```
$ ipcalc 192.168.0.0/16
Address:   192.168.0.0          11000000.10101000. 00000000.00000000
Netmask:   255.255.0.0 = 16     11111111.11111111. 00000000.00000000
Wildcard:  0.0.255.255          00000000.00000000. 11111111.11111111
=>
Network:   192.168.0.0/16       11000000.10101000. 00000000.00000000
HostMin:   192.168.0.1          11000000.10101000. 00000000.00000001
HostMax:   192.168.255.254      11000000.10101000. 11111111.11111110
Broadcast: 192.168.255.255      11000000.10101000. 11111111.11111111
Hosts/Net: 65534                 Class C, Private Internet

```

A nice Java library is the [Commons IP Math](https://github.com/jgonian/commons-ip-math) from **jgonian**.

**Comment by xabolcs** [comment]
> The war packaged application behind reverse proxy doesn't always work well:

This is also true for backends! #94

**Comment by xabolcs** [comment]
@Kuinox: please try the image at ghcr.io!

```
docker pull ghcr.io/openseedbox/openseedbox/server:edge
```

**Comment by Kuinox** [comment]
Yep, it works now, thanks !

**Comment by xabolcs** [comment]
Thanks for the feedvack! Will push the image to Docker Hub later.

**Comment by Kuinox** [comment]
Ok, it now doesn't spit out an error with the reverse proxy, but the downloaded file is empty :/
I know the file is not empty, plex can server this file fine.

**Comment by xabolcs** [comment]
Sad.

I don't use links to backends, but will try to repro your issue on the weekend.
In the mean time you could create a new issue about this.

**Comment by xabolcs** [comment]
`openseedbox/server` image at Docker Hub is fresh now.
![image](https://user-images.githubusercontent.com/568751/198877504-5c6bfa3d-c6c9-463e-b8b1-1fbe05107609.png)
