### ISSUE TITLE
Download link return empty file. Zip is malformed.

### ISSUE THREAD

**Issue by Kuinox** [openseedbox/openseedbox#95]
When downloading a file, the link download a 0b file with the correct name.  
The zip link download a 234 bytes file which is an invalid zip:
![image](https://user-images.githubusercontent.com/18743295/195959758-bbe43251-39b2-4d8c-86bf-486282d96e39.png)

**Comment by xabolcs** [comment]
@gregorkistler, how do you use downloads from backend?
Do you use some context root for backend?
How is your infrastructure?

Same for you, @Kuinox!

Thanks!

**Comment by xabolcs** [comment]
@Kuinox does your backend server have some relevant logs?

**Comment by gregorkistler** [comment]
@xabolcs, I'm using [Traefik](https://traefik.io) as a proxy without zip support since roughly half a year now. Context path isn't set so it uses `root` by default.
As Tomcat serves the files I had to set `xsendfile` to `false`.

Here are the `backend.` specific properties which I've set (variables can be ignored - I'm using a builder script to substitute them in my setup):
```
backend.base.api_key=${OPENSEEDBOX_API_KEY}
backend.base.path=/data
backend.base.device=${OPENSEEDBOX_BACKEND_DEVICE}
backend.base.path.encrypted=false
backend.class=com.openseedbox.backend.transmission.TransmissionBackend
backend.download.scheme=http
backend.autostart=true
backend.download.xsendfile=false
```

and the `openseedbox.` properties of the frontend:
```
openseedbox.node.access=http
openseedbox.zip=false
openseedbox.multizip=false
openseedbox.zip.path=/rdr/
openseedbox.zip.manifestonly=false
openseedbox.context.path=${OPENSEEDBOX_CONTEXT_PATH}
openseedbox.assets.prefix=${OPENSEEDBOX_CONTEXT_PATH}/public
```

@Kuinox mind if you share us your frontend and backend `application.conf`?
Downloading an empty file could have several reasons.
Does your browser console show any errors after you hit the download button?

**Comment by xabolcs** [comment]
> As Tomcat serves the files I had to set `xsendfile` to `false`.

@gregorkistler 
Would you mind show that? I'm interested to incorporate that, as nginx is out.

**Comment by xabolcs** [comment]
I was able to reproduce ... got almost unusable logs! :upside_down_face: 

```
server-node1_1  | 07:32:16,289 TRACE ~ ServletWrapper>service /download/d55be2cd263efa84aeb9495333a4fabc428a4250
server-node1_1  | 07:32:16,290 TRACE ~ httpServletRequest.getContextPath(): 
server-node1_1  | 07:32:16,290 TRACE ~ request.path: /download/d55be2cd263efa84aeb9495333a4fabc428a4250, request.querystring: name=debian-11.5.0-amd64-netinst.iso
server-node1_1  | 07:32:16,291 TRACE ~ ServletWrapper>service, request: GET /download/d55be2cd263efa84aeb9495333a4fabc428a4250?name=debian-11.5.0-amd64-netinst.iso
server-node1_1  | 07:32:16,291 TRACE ~ Route: /download/d55be2cd263efa84aeb9495333a4fabc428a4250 - name=debian-11.5.0-amd64-netinst.iso
server-node1_1  | 07:32:16,291 TRACE ~ ------- public static void controllers.Download.downloadFile(java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException
server-node1_1  | 07:32:16,292 TRACE ~ getActionMethodArgs name [hash] annotation []
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class org.joda.time.DateTime] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class [Lplay.data.Upload;] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class java.util.Calendar] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class [Ljava.io.File;] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [interface play.db.Model$BinaryField] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class [B] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [interface play.data.Upload] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class java.util.Date] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class [[B] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class java.util.Locale] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ directBind: value [d55be2cd263efa84aeb9495333a4fabc428a4250] c [class java.io.File] Class [class java.lang.String]
server-node1_1  | 07:32:16,292 TRACE ~ getActionMethodArgs name [name] annotation []
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class org.joda.time.DateTime] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class [Lplay.data.Upload;] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class java.util.Calendar] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class [Ljava.io.File;] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [interface play.db.Model$BinaryField] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class [B] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [interface play.data.Upload] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class java.util.Date] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class [[B] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class java.util.Locale] Class [class java.lang.String]
server-node1_1  | 07:32:16,293 TRACE ~ directBind: value [debian-11.5.0-amd64-netinst.iso] c [class java.io.File] Class [class java.lang.String]
server-node1_1  | 07:32:16,294 TRACE ~ getActionMethodArgs name [type] annotation []
server-node1_1  | 07:32:16,294 TRACE ~ getActionMethodArgs name [debug] annotation []
```

**Comment by Kuinox** [comment]
Sorry, was busy these last days,  do you need that I try anything ?

**Comment by xabolcs** [comment]
> As Tomcat serves the files I had to set `xsendfile` to `false`.

Thanks @gregorkistler, thats the fix! :+1: 

@Kuinox, please try disable that setting, with a self build Docker images, or a bind mounted `application.conf`:

`docker-compose.yaml`:
```
    volumes:
      - /opt/openseedbox/backends/node1:/media/openseedbox
      - type: bind
        source: /opt/openseedbox/backends/application.conf
        target: /tomcat/webapps/ROOT/WEB-INF/application/conf/application.conf
```

**Comment by xabolcs** [comment]
> Would you mind show that? I'm interested to incorporate that, as nginx is out.

@gregorkistler
Ohh, I thought you used some zero-copy stuff from Tomcat! :sweat_smile:

**Comment by xabolcs** [comment]
Ahh, and `backend.download.ngxzip` should be set to `false`, also.


Looks like the nginx thingies should be wiped out. :confused:

**Comment by gregorkistler** [comment]
> > Would you mind show that? I'm interested to incorporate that, as nginx is out.
> 
> @gregorkistler Ohh, I thought you used some zero-copy stuff from Tomcat! 😅

Ah well, no it's really just the setting in the `application.conf` 😅. Tomcat runs with default settings.



> Ahh, and backend.download.ngxzip should be set to false, also.
>
> Looks like the nginx thingies should be wiped out. 😕

Personally, I've already deactivated the whole zip functionality back then as it wasn't reliable and I could use Nginx images directly from Docker Hub without building custom ones with `mod_zip` support.

**Comment by Kuinox** [comment]
> > As Tomcat serves the files I had to set `xsendfile` to `false`.
> 
> Thanks @gregorkistler, thats the fix! 👍
> 
> @Kuinox, please try disable that setting, with a self build Docker image, or a bind mounted `application.conf`:
> 
> `docker-compose.yaml`:
> 
> ```
>     volumes:
>       - /opt/openseedbox/backends/node1:/media/openseedbox
>       - type: bind
>         source: /opt/openseedbox/backends/application.conf
>         target: /tomcat/webapps/ROOT/WEB-INF/application/conf/application.conf
> ```

Sorry, somehow all the openseedbox data was lost after an auto-upgrade, and I changed my mind how to setup my server (giving up on multiusers) so I won't use openseedbox anymore.

**Comment by xabolcs** [comment]
> Sorry, somehow all the openseedbox data was lost after an auto-upgrade, and I changed my mind how to setup my server (giving up on multiusers) so I won't use openseedbox anymore.

Thats very sad! Sorry about that! :(

**Comment by xabolcs** [comment]
Fixed and Docker images updated.
