### ISSUE TITLE
Try OpenJDK with Eclipse OpenJ9 (aka IBM Semeru) instead the default OpenJDK HotSpot (aka Eclipse Temurin)

### ISSUE THREAD

**Issue by xabolcs** [openseedbox/openseedbox#97]
> **HotSpot** is the VM from the OpenJDK community. It is the most widely used VM today and is used in Oracle’s JDK. It is suitable for all workloads.

> **Eclipse OpenJ9**  is the VM from the Eclipse community. It is an enterprise-grade VM designed for low memory footprint and fast start-up and is used in IBM’s JDK. It is suitable for running all workloads.

----

I read a blogpost with title "[Startup Performance of Tomcat in Docker](https://blog.openj9.org/2020/05/18/startup-performance-of-tomcat-in-docker/)", it starts with:
> Tomcat startup time is reduced by ~30% by enabling the Shared Class Cache (SCC) in the Docker images.

It looks like the cache size can be controlled (maybe by the `-Xscmx` parameter) which will be an added weight to the container:
> ```
> Docker Image                    SIZE
> tomcat_explicitscc:latest       366MB
> tomcat:latest                   345MB
> ```

Let's try if it's worth it!

**Comment by xabolcs** [comment]
I'm wondering if  warming up with OpenSeedbox would make sense.

**Comment by gregorkistler** [comment]
🚨 One thing to keep in mind is the lack of armv7/armhf support of OpenJ9. They only provide amd64, arm64, ppc64le and s390x zipped/packaged binaries.
According to an older https://github.com/eclipse-openj9/openj9/issues/1159#issuecomment-470661932 there won't be any more work going on regarding this specific ISA.

So for our project this would mean we only build containers for `linux/amd64` and `linux/arm64` 😢

I've personally tried to switch to OpenJ9 a couple of times and always reverted back due to image size increase. Couldn't really see any startup time improvement as the application itself is kinda tiny compared to Java applications like Jira and starts up in ~6000 milliseconds on a 4 core 3.0 GHz Ampere Altra Arm Oracle Cloud instance.
Don't have any comparing numbers for OpenJ9 anymore but it was about the same time.

If you're already doing some test runs would be great to see current comparisons as my experiences are outdated 🤓

**Comment by xabolcs** [comment]
Same test (again) with HotSpot OpenJDK:
* backend: 2514 and 15436 ms
* frontend: 2849 and 17236 ms

With Eclipse OpenJ9:
* backend: 2382 and 17244 ms
* frontend: 3070 and 19496 ms

And both have their few seconds error. :shrug: 

But the images are heavier:
```bash
# docker image ls openseedbox/server:*
REPOSITORY           TAG          IMAGE ID       CREATED          SIZE
openseedbox/server   dockerfile   53730a6b00e2   15 minutes ago   202MB
openseedbox/server   latest       f1faf98b147b   40 hours ago     188MB
# docker image ls openseedbox/client:*
REPOSITORY           TAG          IMAGE ID       CREATED          SIZE
openseedbox/client   dockerfile   4e5b153f97e2   18 minutes ago   208MB
openseedbox/client   latest       c3136344443e   39 hours ago     195MB
```

Keep using Eclipse Temurin. :woman_shrugging:

**Comment by xabolcs** [comment]
For the record: I used `ibm-semeru-runtimes:open-11-jdk` Docker image to build `openseedbox/base` and `openseedbox/tomcat` to use them in `openseedbox/client` and `openseedbox/server`.

```diff
diff --git a/Dockerfile b/Dockerfile
index cbf8461..f716635 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,7 +3,7 @@
 FROM debian:bullseye-slim AS base-image
 
 
-FROM eclipse-temurin:11-jdk AS java
+FROM ibm-semeru-runtimes:open-11-jdk AS java
 RUN jlink \
         --add-modules \
                 java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.prefs,java.rmi,java.scripting,java.security.jgss,java.security.sasl,java.sql,java.sql.rowset,java.transaction.xa,java.xml,jdk.crypto.cryptoki,jdk.jdi,jdk.management,jdk.unsupported \
```

**Comment by gregorkistler** [comment]
Thanks. So in the end more drawbacks than with HotSpot.

**Comment by xabolcs** [comment]
The lack of armv7/armhf support of OpenJ9 is still a showstopper but I have to note that the warmup stuff is a real thing.

Just noticed that the official images are using this SCC feature actively (with Apache Tomcat 9):

```bash
$ docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' ibm-semeru-runtimes:open-11-jre 
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_VERSION=jdk-11.0.17+8_openj9-0.35.0
JAVA_HOME=/opt/java/openjdk
JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+PortableSharedCache -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal
```

And the warmup command:
```bash
$ docker inspect --format='{{range .ContainerConfig.Cmd}}{{println .}}{{end}}' ibm-semeru-runtimes:open-11-jre 
/bin/sh
-c
set -eux;     unset OPENJ9_JAVA_OPTIONS;     SCC_SIZE="50m";     DOWNLOAD_PATH_TOMCAT=/tmp/tomcat;     INSTALL_PATH_TOMCAT=/opt/tomcat-home;     TOMCAT_CHECKSUM="0db27185d9fc3174f2c670f814df3dda8a008b89d1a38a5d96cbbe119767ebfb1cf0bce956b27954aee9be19c4a7b91f2579d967932207976322033a86075f98";     TOMCAT_DWNLD_URL="https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz";         mkdir -p "${DOWNLOAD_PATH_TOMCAT}" "${INSTALL_PATH_TOMCAT}";     curl -LfsSo "${DOWNLOAD_PATH_TOMCAT}"/tomcat.tar.gz "${TOMCAT_DWNLD_URL}";     echo "${TOMCAT_CHECKSUM} *${DOWNLOAD_PATH_TOMCAT}/tomcat.tar.gz" | sha512sum -c -;     tar -xf "${DOWNLOAD_PATH_TOMCAT}"/tomcat.tar.gz -C "${INSTALL_PATH_TOMCAT}" --strip-components=1;     rm -rf "${DOWNLOAD_PATH_TOMCAT}";         java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal,createLayer -Xscmx$SCC_SIZE -version;     export OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal";     "${INSTALL_PATH_TOMCAT}"/bin/startup.sh;     sleep 5;     "${INSTALL_PATH_TOMCAT}"/bin/shutdown.sh -force;     sleep 15;     FULL=$( (java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,printallStats 2>&1 || true) | awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}');     DST_CACHE=$(java -Xshareclasses:name=dry_run_scc,cacheDir=/opt/java/.scc,destroy 2>&1 || true);     SCC_SIZE=$(echo $SCC_SIZE | sed 's/.$//');     SCC_SIZE=$(awk "BEGIN {print int($SCC_SIZE * $FULL / 100.0)}");     [ "${SCC_SIZE}" -eq 0 ] && SCC_SIZE=1;     SCC_SIZE="${SCC_SIZE}m";     java -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal,createLayer -Xscmx$SCC_SIZE -version;     unset OPENJ9_JAVA_OPTIONS;         export OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,bootClassesOnly,nonFatal";     "${INSTALL_PATH_TOMCAT}"/bin/startup.sh;     sleep 5;     "${INSTALL_PATH_TOMCAT}"/bin/shutdown.sh -force;     sleep 5;     FULL=$( (java -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,printallStats 2>&1 || true) | awk '/^Cache is [0-9.]*% .*full/ {print substr($3, 1, length($3)-1)}');     echo "SCC layer is $FULL% full.";     rm -rf "${INSTALL_PATH_TOMCAT}";     if [ -d "/opt/java/.scc" ]; then           chmod -R 0777 /opt/java/.scc;     fi;         echo "SCC generation phase completed";

```
